spring:
  datasource:
    url: jdbc:postgresql://postgres-user:5432/userDB
    username: postgres
    password: postgres
    config:
      activate:
        on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQL81Dialect
